#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,45&i=&v= */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define I2S_INTERNAL		true

// missing in defaults for IRRemoteESP8266 lib!
// best default value and you can list requred IR protocols - like DECODE_RC6, SEND_RC6
#define _IR_ENABLE_DEFAULT_ false
#define IR_PIN			255

#endif
