; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.filesystem = spiffs

;Classic YORADIO
;board_build.partitions = min_spiffs.csv   ; <<< minimal SPIFFS aka (1.9MB APP with OTA, 300KB SPIFFS)


;https://github.com/espressif/arduino-esp32/blob/master/tools/partitions

; BT sender version
; aplikace presahujici 1.9 nebude mit na takovem wroom32 podporu OTA
board_build.flash_size = 4MB
board_build.partitions = huge_app.csv
;----

lib_deps =
  https://github.com/pschatzmann/ESP32-A2DP
  https://github.com/pschatzmann/arduino-audio-tools.git

; ------------------
; Compilation mode
; ------------------
build_type = debug      ;Only changed files
;build_type = release   ;Full recompile


monitor_speed = 115200
upload_speed = 921600

; Optimalizace
build_flags = 
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

build_unflags = -O2
